pipeline:
  identifier: Build_harnesscd_example_apps_1692892128102
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Ironmanburns/harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    connectorRef: account.harnessImage
                    image: hello-world:linux
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Mac_cluster
              namespace: harness-namespace-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        delegateSelectors:
          - terraform-delegate
